// Eén huisstijl voor alle sites: het design van nexy.help (rustig, smalle leeskolom, kicker, standfirst, antwoordblok, kaarten, rijen, FAQ),
// per site alleen een andere accentkleur. look({acc, acc2, accD, acc2D}, {dark}) -> CSS-tekst.
// Bevat ook de oude klassenamen (.hero, .q, .opt, .pr, .txt, .card, .grid, .disc, .box) zodat bestaande pagina's meteen meeveranderen.
export const ACCENTS = {
  keuzehulp: { acc: '#0f766e', acc2: '#e6f4f1', accD: '#5eead4', acc2D: '#0f2624' }, // groenblauw
  whichtobuy: { acc: '#c2410c', acc2: '#fff1e8', accD: '#fdba74', acc2D: '#2a1a10' }, // oranje
  kaufberater: { acc: '#6d28d9', acc2: '#f1ebff', accD: '#c4b5fd', acc2D: '#1d1630' }  // violet
};
export function look(a, o) {
  o = o || {}; const dark = o.dark !== false;
  const darkVars = `--ink:#f3f5f8;--ink-2:#c3c9d4;--ink-3:#8d95a3;--line:#262b36;--bg:#0c0e13;--bg-2:#13161d;--acc:${a.accD};--acc-2:${a.acc2D};--on-acc:#0c0e13`;
  return `:root{--ink:#10131a;--ink-2:#3c4350;--ink-3:#6b7280;--line:#e4e7ec;--bg:#ffffff;--bg-2:#f7f8fa;--acc:${a.acc};--acc-2:${a.acc2};--on-acc:#fff;--max:46rem}
${dark ? `@media (prefers-color-scheme:dark){:root:not([data-theme=light]){${darkVars}}}:root[data-theme=dark]{${darkVars}}` : ''}
*{box-sizing:border-box}html{-webkit-text-size-adjust:100%}body{margin:0;background:var(--bg);color:var(--ink);font:400 1.0625rem/1.65 ui-sans-serif,-apple-system,"Segoe UI",Inter,Roboto,Helvetica,Arial,sans-serif;text-rendering:optimizeLegibility}a{color:var(--acc)}
.wrap{max-width:var(--max);margin:0 auto;padding:0 16px}.topbar{border-bottom:1px solid var(--line);background:var(--bg)}.topbar .wrap{display:flex;align-items:center;gap:16px;height:60px}
.mark{font-weight:700;font-size:1.25rem;letter-spacing:-.02em;color:var(--ink);text-decoration:none}.mark em{color:var(--acc);font-style:normal}.topnav{margin-left:auto;display:flex;gap:18px;font-size:.9375rem}.topnav a{color:var(--ink-2);text-decoration:none}.topnav a:hover{color:var(--acc)}
main{padding:28px 0 8px}.crumbs,.crumbs a{color:var(--ink-3)}.crumbs{font-size:.875rem;margin:0 0 18px}.kicker{font-size:.75rem;letter-spacing:.09em;text-transform:uppercase;color:var(--acc);font-weight:650;margin:0 0 10px}
h1{font-size:clamp(1.9rem,5.2vw,2.75rem);line-height:1.12;letter-spacing:-.025em;margin:0 0 14px;font-weight:700}h2{font-size:1.375rem;line-height:1.25;letter-spacing:-.015em;margin:40px 0 12px;font-weight:700}h3{font-size:1.0625rem;margin:26px 0 8px;font-weight:650}
.standfirst,.lead{font-size:1.1875rem;color:var(--ink-2);margin:0 0 26px;line-height:1.5}.meta{font-size:.875rem;color:var(--ink-3);margin:0 0 12px}
.answer{background:var(--bg-2);border:1px solid var(--line);border-left:3px solid var(--acc);border-radius:10px;padding:18px 20px;margin:0 0 30px}.answer p{margin:0}.answer p+p{margin-top:10px}.answer strong{color:var(--ink)}
.rows{border:1px solid var(--line);border-radius:10px;overflow:hidden;margin:0 0 8px}.rows .r{display:grid;grid-template-columns:11.5rem 1fr;border-bottom:1px solid var(--line)}.rows .r:last-child{border-bottom:0}.rows .r>span:first-child{padding:12px 14px;font-weight:650;background:var(--bg-2);font-size:.9375rem}.rows .r>span:last-child{padding:12px 14px;color:var(--ink-2)}@media (max-width:560px){.rows .r{grid-template-columns:1fr}.rows .r>span:first-child{border-bottom:1px solid var(--line)}}
details.faq{border-bottom:1px solid var(--line);padding:2px 0}details.faq summary{cursor:pointer;padding:13px 0;font-weight:650;list-style:none;display:flex;gap:10px;align-items:flex-start}details.faq summary::-webkit-details-marker{display:none}details.faq summary:before{content:"+";color:var(--acc);font-weight:700;line-height:1.5}details.faq[open] summary:before{content:"\\2013"}details.faq .a{padding:0 0 15px 22px;color:var(--ink-2)}details.faq .a p{margin:0}
.rel{font-size:.9375rem;color:var(--ink-2);margin:28px 0 0}
.cards,.grid{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(15rem,1fr));margin:18px 0 0;padding:0;list-style:none}.cards li,.card{border:1px solid var(--line);border-radius:10px;padding:14px 16px;background:var(--bg-2);display:block;text-decoration:none;color:var(--ink)}.cards a,.card h3{font-weight:650;text-decoration:none;letter-spacing:-.01em;color:var(--acc);font-size:1rem;margin:0}.card:hover{border-color:var(--acc)}.cards p,.card p{margin:6px 0 0;font-size:.9063rem;color:var(--ink-3);line-height:1.45}.card .cat,.card .c{font-size:.6875rem;letter-spacing:.08em;text-transform:uppercase;color:var(--ink-3);margin:0 0 4px}
.pills{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 22px;padding:0;list-style:none}.pills li{font-size:.75rem;border:1px solid var(--line);border-radius:999px;padding:4px 10px;color:var(--ink-3)}
.sub,.box,.txt,.q{border:1px solid var(--line);border-radius:12px;padding:20px;margin:16px 0 0;background:var(--bg-2)}.sub h2,.box h2,.txt h2,.q h2{margin:0 0 8px;font-size:1.125rem}.sub p{margin:0 0 14px;color:var(--ink-2);font-size:.9375rem}.box ul,.txt ul{margin:0;padding-left:20px}.box li,.txt li{margin:6px 0;color:var(--ink-2)}.box.ai{border-left:3px solid var(--acc)}
.sub form{display:flex;gap:8px;flex-wrap:wrap}.sub input[type=email],input[type=email]{flex:1 1 13rem;min-width:0;padding:11px 13px;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:var(--ink);font-size:1rem;font-family:inherit}
.btn{display:inline-block;padding:11px 16px;border-radius:8px;border:1px solid var(--acc);background:var(--acc);color:var(--on-acc);font:inherit;font-weight:650;font-size:.9375rem;cursor:pointer;text-decoration:none}.btn.ghost,.btn.sec{background:transparent;color:var(--acc)}.btn:disabled{opacity:.55;cursor:default}
.note{font-size:.8125rem;color:var(--ink-3);margin:12px 0 0}.pushrow{margin:12px 0 0;display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.hero{padding:6px 0 0}.hero h1{margin-bottom:10px}.hero p{font-size:1.1875rem;color:var(--ink-2);margin:0 0 18px;line-height:1.5}
.opts{display:flex;flex-wrap:wrap;gap:8px}.opt{border:1px solid var(--line);background:var(--bg);border-radius:999px;padding:9px 15px;font:inherit;font-weight:600;font-size:.9375rem;cursor:pointer;color:var(--ink)}.opt:hover{border-color:var(--acc)}.opt.on{background:var(--acc);border-color:var(--acc);color:var(--on-acc)}
.adv{margin:18px 0}.pr{display:grid;grid-template-columns:96px 1fr;gap:14px;background:var(--bg);border:1px solid var(--line);border-radius:12px;padding:14px;margin:0 0 10px;align-items:center}.pr.best{border:1px solid var(--acc);box-shadow:0 0 0 3px var(--acc-2)}.pr img{width:96px;height:96px;object-fit:contain;border-radius:8px;background:#fff}.pr .role,.role{font-size:.6875rem;letter-spacing:.08em;text-transform:uppercase;color:var(--acc);font-weight:700}.pr .t,.t{font-weight:650;margin:2px 0 4px;line-height:1.3}.pr .m{color:var(--ink-3);font-size:.875rem;margin-bottom:8px}.pr .m b,.price{color:var(--ink);font-size:1.0625rem;font-weight:700}.pr .m s{color:var(--ink-3);margin-left:6px}
.disc{color:var(--ink-3);font-size:.8125rem;margin:14px 0 0}
footer{border-top:1px solid var(--line);margin:48px 0 0;padding:22px 0 44px;font-size:.875rem;color:var(--ink-3)}footer a{color:var(--ink-3)}footer .fl{display:flex;flex-wrap:wrap;gap:14px;margin:0 0 10px}
@media(max-width:600px){.pr{grid-template-columns:72px 1fr;gap:12px}.pr img{width:72px;height:72px}}`;
}
